name: "Linting"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pylint:
    name: Python Code Quality and Lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-latest]
        linter-env: ["linting", "type_check"]
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run linting
        if: matrix.linter-env == 'linting'
        run: |
          uv run --group linting pylint bomf
      - name: Run type_check
        if: matrix.linter-env == 'type_check'
        run: |
          uv run --group type_check mypy --show-error-codes --check-untyped-defs src/bomf
          uv run --group type_check mypy --show-error-codes --check-untyped-defs unittests
